### ISSUE TITLE
cds deploy --vcap-file default-env.json does not utilize the TARGET_CONTAINER and VCAP_SERVICES defined in the default-env.json file

### ISSUE THREAD

**Issue by CzynJay** [cap-js-community/feature-toggle-library#81]
As per in the title, when using cds deploy --vcap-file of the default-env.json, thhe deployment is not utilizing the TARGET_CONTAINER defined in the default-env.json file, instead it is using the resources defined in the mta.yaml file.

**Comment by rlindner81** [comment]
@CzynJay how does this relate to the feature toggle library?

**Comment by CzynJay** [comment]
Hi @rlindner81 I apologize if this is the wrong library to raise an issue. Do you know which library I should raise an issue regarding cds deploy issues? This is in relation to this: [Using cds deploy for Ad-Hoc Deployments ](https://cap.cloud.sap/docs/guides/databases-hana#cds-deploy-vcap-file-someenvfile-json)

**Comment by rlindner81** [comment]
CDS itself is not on github.com, so you cannot open an issue directly.

Reading https://cap.cloud.sap/docs/resources/#support-channels 
I would say your issue falls under the component
- `BC-XS-CDX-TLS` for Tools, IDEs, Build, Deployment
